### ISSUE TITLE
[BUG] missing files "NOCITY.gli" and "NOCITY.glj" crash game

### ISSUE THREAD

**Issue by mr-dev-cmd** [WizzardMaker/AirlineTycoon#22]
**Your current version**
V1.6 - Ubuntu Linux 22.04 (german retail version)

**Describe the bug**
When looking in the city Information and click on a City with no pictures, the game look for a non existing file "NOCITY"

**To Reproduce**
1. Go to office or Laptop
2. Click on globe/filofax
3. Click on the city menu
4. click on a city with no picture (e.g. Wellington)

**Expected behavior**
Just show the detailed city information pages.
Only cities with provided pictures should show additional picture pages.

**Additional context**
Due to Linux case sensitivity, all City gli and glj files must be upper case. Would be nice if all files of the game could stay lowercase. So it's easier to rename everything by script when preparing the old Windows game folder for Linux.

**Comment by WizzardMaker** [comment]
So, you want that all game files should be lower case?

**Comment by mr-dev-cmd** [comment]
That would make it easier if everything the same, yes.
But its not really a bug. More a "nice to have".

The missing "nocity" files are actually the bug. I worked around by copying another city file and renamed it to nocity. Maybe it can be better done in the code.

**Comment by WizzardMaker** [comment]
The game crashing bug is fixed by 1c50f7e17ef45185a09c0f5131c03f8aae875ca7

The other point should be moved to a different issue for further discussion

**Comment by mr-dev-cmd** [comment]
I tested with Wellington. The first Click on the city brings no error anymore, but when you click on the Information page (yellow) and then back on the City (blue) it still crash and ask for the NOCITY file.

**Comment by mr-dev-cmd** [comment]
In case of a City that actually have pictures, but the file is missing, the game crash now without message when you navigate to the page where the picture should be.
It's not yet a good solution. Before I got at least a message that tell me the problem.
It's better to only ignore missing NOCITY.* files.
(But as I mentioned above, even this is not fully working yet. I will try to add screenshots for better explanation)

**Comment by WizzardMaker** [comment]
Yeah, I've now changed how the game handles the loading and displaying of those images (596c74cad1c4f2891dd74837a09f0a366c171543)

The game now removes the image pages when it can't find the image files

This is untested on the Laptop, but should also work

**Comment by mr-dev-cmd** [comment]
Very nice. I tested on filofax and laptop. Both worked well. No crash but some lines in the log file. And in case there are files available it shows the pictures. Good solution 👌
